sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: sku
        field:
          input_type: number
          antlers: false
          display: SKU
          type: text
          icon: text
          width: 33
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: quantity
        field:
          input_type: number
          antlers: false
          display: Quantity
          type: text
          icon: text
          width: 33
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: price
        field:
          input_type: number
          antlers: false
          display: Price
          type: text
          icon: text
          width: 33
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: description
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: Description
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
          read_only: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
title: Products
